basePath: /
consumes:
- application/json
definitions:
  models.Product:
    description: Retrive the product data structure
    properties:
      company:
        type: string
      drug_generic:
        type: string
      id:
        type: integer
      product_name:
        type: string
      score:
        type: number
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample Simple Elasticsearch Product.
  title: Elasticsearch Example
  version: "1.0"
paths:
  /products:
    get:
      consumes:
      - application/json
      description: Retrieves a list of products with optional pagination and search
        keywords
      parameters:
      - description: Limit number of results
        in: query
        name: limit
        type: integer
      - description: Offset for pagination
        in: query
        name: offset
        type: integer
      - description: Search keyword
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Product'
            type: array
      summary: Get Products
      tags:
      - Products
produces:
- application/json
schemes:
- http
swagger: "2.0"
